spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/youmiteru-n2 #//Your DB
    username: postgres  #//Your name
    password: 123 #//Your password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    locations: classpath:db/migration
    default-schema: flyway_schema
server:
  port: 8081
